# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'PaHis' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaHis

    pod 'Kingfisher', '~> 4.0'

    pod 'Firebase/Database'

    pod 'Firebase/Storage'

    pod 'Firebase/Auth'

    pod 'Firebase/Core'
    
    pod 'GoogleMaps'
    
    pod 'LocationPickerViewController'

end
